Repository HBNU-SWUNIV/come-capstone23-kjj, pull requests merged in 2023-10, with the labels that each got.

#84 refactor: modification of entity based on TDA roles
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/menu/Menu.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/order/Order.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/user/User.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/user/UserPolicy.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/leftover/LeftoverServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/menu/MenuServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/order/OrderServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/user/UserKeycloakServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/user/UserServiceImplV1.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreateCalculatePreTasklet.java
Labels: refactoring

#82 feat: create chart
  003Code/Frontend/src/components/Dayoff/Calander2.js
  003Code/Frontend/src/components/Drawerheader/Drawerheader.js
  003Code/Frontend/src/components/Main/MenuStatisticsChart.js
  003Code/Frontend/src/components/Menu/MenuCard.js
  003Code/Frontend/src/screens/Dashboard.js
  003Code/Frontend/src/screens/Menus.js
Labels: new feature

#87 feat: batch process bug fix
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/aop/ServiceExceptionHandlingAspect.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auto_init/InitRun.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/config/KeycloakConfig.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/order/OrderUserApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/store/StoreManagerApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/user/UserApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/user/user/UserDatePolicyDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/calculate/CalculatePre.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/user/UserPolicy.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/handler/controller/ControllerExceptionHandler.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/handler/filter/ExceptionHandlerBeforeKeycloak.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/handler/filter/ExceptionHandlerBeforeUsernamePassword.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/handler/filter/template/ExceptionTemplate.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/handler/filter/template/SetFilterErrorResponse.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/order/OrderService.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/order/OrderServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/user/UserServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/user/service/UserService.java
  003Code/Backend/api/src/test/java/com/hanbat/zanbanzero/controller/user/UserApiControllerTest.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/aspect/SlackAspect.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/handler/ConnectionHandler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/handler/ConnectionHandlerV1.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/handler/ExceptionRunnable.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/OrderStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/PredictWeekStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CountOrdersByDateTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreatePredictUserWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreatePredictWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/object/FoodPredict.java
  
Labels: fix

#89 bug: auto refresh
  003Code/Frontend/src/api/reissue.js
  003Code/Frontend/src/auth/Auth.js
  003Code/Frontend/src/components/charts/FoodSavingStatusChart.js
  003Code/Frontend/src/components/charts/UserStatisticsChart.js
  003Code/Frontend/src/domains/nav/Nav.js
  003Code/Frontend/src/router.js
  003Code/Frontend/src/router/ErrorBoundary.js
Labels: bug

#90 feat: create sales-based & service-based food ingredient data generate logic
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/store/StoreManagerApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/sbiz/EntireData.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/sbiz/PartData.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/sbiz/WeeklyFoodPredictDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/menu/MenuFood.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/sbiz/WeeklyFoodPredict.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/repository/sbiz/SbizRepository.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/store/StoreService.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/store/StoreServiceImplV1.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreatePredictUserWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreatePredictWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/CreateTodayOrder.java
  003Code/Backend/batch/src/main/java/com/batch/batch/object/FoodPredict.java
  003Code/Backend/batch/src/main/java/com/batch/batch/tools/DateTools.java
Labels: new feature

#92 refactor: Keycloak Filter refactoring
  003Code/Backend/api/build.gradle
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/aop/ServiceExceptionHandlingAspect.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auth/login/filter/KeycloakLoginFilterV2.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/config/SecurityConfig.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/order/OrderUserApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/order/OrderDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/entity/order/Order.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/tool/SlackTools.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/order/OrderService.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/order/OrderServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/user/UserKeycloakServiceImplV1.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/aspect/SlackAspect.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/CalculateStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/OrderStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/PredictWeekStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/CreateCalculatePreTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/CreateLeftoverPreTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/order/CountOrdersByDateTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/order/CreateTodayOrder.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/CreatePredictUserWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/CreatePredictWeekTasklet.java
Labels: refactoring, new feature

#95 perf: solved problem of duplicate Slack message transmission by AOP
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/aop/ServiceExceptionHandlingAspect.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/exception/tool/SlackTools.java
  003Code/Backend/api/src/main/resources/application.yml
Labels: chore, performance

#96 feat: apply file logging system by logback
  .idea/workspace.xml
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/aop/ExceptionHandlingAspect.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auth/jwt/JwtUtil.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auth/login/authentication_impl/AuthenticationProviderImpl.java
  003Code/Backend/api/src/main/resources/logback-spring.xml
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/order/CountOrdersByDateTasklet.java
Labels: new feature

#102 chore: update today menu design
  003Code/Frontend/src/components/todaymenu/TodayMenuAddDialog.js
  003Code/Frontend/src/components/todaymenu/TodayMenuCalander.js
  003Code/Frontend/src/components/todaymenu/TodayMenuInputDialog.js
  003Code/Frontend/src/domains/nav/Nav.js
  003Code/Frontend/src/domains/pages/Dayoff.js
  003Code/Frontend/src/domains/pages/TodayMenu.js
  003Code/Frontend/src/index.js
  003Code/Frontend/src/styles/reset.css
Labels: chore

#104 feat: update batch logic
  003Code/Backend/api/.gitignore
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auto_init/InitRun.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auto_init/dto/ReqBody.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/auto_init/dto/ReqMessage.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/config/SecurityConfig.java
  003Code/Backend/api/src/main/resources/application.yml
  003Code/Backend/batch/build.gradle
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/aop/aspect/SlackAspect.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/CalculateStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/OrderStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/step/PredictWeekStep.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/CreateCalculatePreTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/CreateLeftoverPreTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/method/CreateCalculatePreMethod.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/calculate/method/CreateLeftoverPreMethod.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/order/CountOrdersByDateTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/order/method/CountOrdersByDateMethod.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/CreatePredictUserWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/CreatePredictWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/method/CreatePredictUserWeekMethod.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/method/CreatePredictWeekMethod.java
  003Code/Backend/batch/src/main/java/com/batch/batch/tools/DateTools.java
Labels: new feature

#105 feat: update batch
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/BatchScheduler.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/CreatePredictUserWeekTasklet.java
  003Code/Backend/batch/src/main/java/com/batch/batch/batch/order/task/predictweek/method/CreatePredictUserWeekMethod.java
Labels: new feature

#109 feat: update manager home api
  003Code/Backend/README.md
  003Code/Backend/api/.gitignore
  003Code/Backend/api/build.gradle
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/controller/store/StoreManagerApiController.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/store/StorePreDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/store/StoreSalesDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/dto/store/StoreTodayDto.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/repository/calculate/CalculateRepository.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/repository/order/OrderRepository.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/menu/MenuServiceImplV1.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/store/StoreService.java
  003Code/Backend/api/src/main/java/com/hanbat/zanbanzero/service/store/StoreServiceImplV1.java
  README.md
Labels: new feature, docs

#110 chore: statistics costs
  003Code/.DS_Store
  003Code/Frontend/src/api/apis.js
  003Code/Frontend/src/components/StatisticsWrap.js
  003Code/Frontend/src/components/general/Statistics.js
  003Code/Frontend/src/hooks/UseCalculateFood.js
  003Code/Frontend/src/hooks/UseGetCharts.js
  003Code/Frontend/src/hooks/dashboard_statistics/UseCompareReservation.js
  003Code/Frontend/src/hooks/dashboard_statistics/UsePredictPop.js
  003Code/Frontend/src/hooks/dashboard_statistics/UseUserPop.js
Labels: chore
